### ISSUE TITLE
Dataset Missing

### ISSUE THREAD

**Issue by ravikumarmn** [linas-p/EVDPEP#1]
I looked at your paper and liked it. I want to implement paper.  Could you provide me the dataset. Please.

Email Id : ravikumarnaduvin@gmail.com

Thanks.

**Comment by linas-p** [comment]
The link to used VED dataset 
[link](https://drive.google.com/drive/folders/1NxGQzGXARK7qCSMHlsuL-Ovrl-0itisL?usp=sharing)
added in recent commit.

**Comment by ravikumarmn** [comment]
Thank you so much. :+1:
